Improvements
charlesdevandiere/xmldoc2md pull request #26
Opened 2023-04-23 09:35 UTC by TimothyMakkison

Resolves #15, #16 and #21. Not sure about the argument names/ whether some should be enabled by default or not.

### TypeId in Attributes
Adds the argument "--hide-typeid", which, when enabled, will exclude documentation for the default `TypeId: object` property exposed by types inheriting from `Attribute`. Note that `TypeId` will still be documented if it's implemented in the derived class.

### Show obsolete
When using the argument "--warn-obsolete", types and members marked with the `Obsolete` attribute will have a paragraph stating that the value is deprecated. If the `Obsolete` attribute is supplied with a warning message, then that will be used instead. I copied the Microsoft docs and placed this warning before `WriteMemberInfoSummary`, using similar language. The current default message could be improved, and perhaps the warning could be lowered to be in front of `WriteMemberInfoRemarks`.

### Show private methods
The argument "--private-method" will document both public and private methods.

2023-05-02 09:58 UTC, charlesdevandiere requested changes
Thank you very much for these particularly useful improvements!

2023-05-02 09:58 UTC, charlesdevandiere commented on sample/MyClassLib/MyObsoleteClass.cs
> +        [Obsolete("Deprecated in favor or MyClass.")]
Did you mean this "Deprecated in favor of MyClass." ?

2023-05-02 09:58 UTC, charlesdevandiere commented on src/XMLDoc2Markdown/Program.cs
> +        CommandOption IncludePrivateMethodOption = app.Option(
I think it's best to show anything private including properties, fields etc, not just methods.

2023-05-02 09:58 UTC, charlesdevandiere commented on src/XMLDoc2Markdown/Program.cs
> +        CommandOption WarnObsoleteOption = app.Option(
I think this can be enabled in any case, no need to make it an option.

2023-05-02 09:58 UTC, charlesdevandiere commented on src/XMLDoc2Markdown/TypeDocumentation.cs
> +            WriteObsolete(attribute, this.document, "This type has been deprecated.");
According to the warning from MSBuild, I think the message should instead be: "This type is obsolete."

2023-05-02 09:58 UTC, charlesdevandiere commented on src/XMLDoc2Markdown/TypeDocumentation.cs
> +            WriteObsolete(attribute, this.document, "This member has been deprecated.");
According to the warning from MSBuild, I think the message should instead be: "This member is obsolete."

2023-05-02 09:58 UTC, charlesdevandiere commented on src/XMLDoc2Markdown/Program.cs
> +        CommandOption HideTypeIdOption = app.Option(
When looking at Microsoft's Obsolete attribute documentation, one can see the TypeId property. Therefore, I think the HideTypeId option is undesirable.

2023-05-02 09:58 UTC, charlesdevandiere commented on src/XMLDoc2Markdown/Properties/launchSettings.json
> +      "commandLineArgs": "../../../../../sample/MyClassLib/bin/Debug/netstandard2.0/MyClassLib.dll ../../../../../docs/sample --examples-path ../../../../../sample/docs/examples --github-pages --back
Can you also add these arguments in the `generate-sample-doc.bat` file please?

2023-05-02 22:25 UTC, TimothyMakkison commented on src/XMLDoc2Markdown/Program.cs
> +        CommandOption IncludePrivateMethodOption = app.Option(
Should this be generic like `--private-members` or should I create `--private-fields`, `--private-properties` etc?

2023-05-02 22:25 UTC, TimothyMakkison commented on src/XMLDoc2Markdown/Program.cs
> +        CommandOption HideTypeIdOption = app.Option(
Fair enough, you should close #15 then. I'm guessing the desire was to avoid documenting the irrelevant property when it wasn't overriden/used to avoid confusing readers of the documentation.

2023-05-09 12:37 UTC, charlesdevandiere commented
The reply button is not working today so I put all my comments here.

The `--private-members` option name is perfect.

I see that retrieving private members brings up BackingFields. Is it possible to ignore them? If this is not the case, we can exclude the fields from the retrieving of private members in this first version.

Sorry, I made a mistake in my comment last week: Can you restore the [generate-sample-doc.bat](https://github.com/charlesdevandiere/xmldoc2md/blob/master/generate-sample-doc.bat) file so that the private members are not displayed in the example please?

2023-05-09 15:35 UTC, charlesdevandiere commented
Great! Can you please run the bat file to regenerate the sample without the private members?

2023-05-11 14:30 UTC, charlesdevandiere approved these changes

2023-05-11 14:32 UTC, TimothyMakkison commented
Sorry please don't merge this yet. I havent resolved the conflicts 🙏

2023-05-11 14:40 UTC, merged

2023-05-11 14:42 UTC, charlesdevandiere commented
No problem, I resolved conflicts. Thank you very much for your contribution !

2023-05-11 16:46 UTC, TimothyMakkison commented
Nice! Thanks for doing that, VS auto merge was being a pain and kept overwriting my changes.